efs/efs/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views

from efsusers.views import SignUpView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    re_path(r'^accounts/login/$', LoginView.as_view(template_name='accounts/login.html'), name="login"),
    re_path(r'^accounts/logout/$', LogoutView.as_view(), LogoutView.next_page, name="logout"),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='accounts/password_reset_form.html'), name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name = 'accounts/password_reset_complete.html'), name='password_reset_complete'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name ='accounts/password_change_form.html'), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name = 'accounts/password_change_done.html'), name='password_change_done'),

]

efs/portfolio/urls.py
from django.conf.urls import url
from . import views
from django.urls import path, re_path
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework import routers

from .views import ChartData

app_name = 'portfolio'

# router = routers.DefaultRouter()
# router.register(r'customers_json', views.CustomerList)

urlpatterns = [

    path('', views.home, name='home'),
    re_path(r'^home/$', views.home, name='home'),
    path('customer_list', views.customer_list, name='customer_list'),
    path('customer/<int:pk>/edit/', views.customer_edit, name='customer_edit'),
    path('customer/<int:pk>/delete/', views.customer_delete, name='customer_delete'),
    path('stock_list', views.stock_list, name='stock_list'),
    path('stock/create/', views.stock_new, name='stock_new'),
    path('stock/<int:pk>/edit/', views.stock_edit, name='stock_edit'),
    path('stock/<int:pk>/delete/', views.stock_delete, name='stock_delete'),
    path('investment_list/', views.investment_list, name = 'investment_list'),
    path('investment/<int:pk>/edit/', views.investment_edit, name = 'investment_edit'),
    path('investment/create/', views.investment_new, name='investment_new'),
    path('investment/<int:pk>/delete/', views.investment_delete, name='investment_delete'),
    path('customer/<int:pk>/portfolio/', views.portfolio, name='portfolio'),
    path('customers_json/', views.CustomerList.as_view()),
    path('customer/<int:pk>/portfolio/pdf/', views.generate_pdf_view, name='generate_pdf_view'),
    path('customer/<int:cust_pk>/piechart/', views.pie_chart, name='pie-chart'),
    path('customer/<int:pk>/bar-chart/',ChartData.as_view(), name = 'chartdata'),
]

efs/portfolio/models.py
from django.db import models

from django.utils import timezone
import requests


# Create your models here.
class Customer(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=200)
    cust_number = models.IntegerField(blank=False, null=False)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zipcode = models.CharField(max_length=10)
    email = models.EmailField(max_length=200)
    cell_phone = models.CharField(max_length=50)
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.cust_number)


class Investment(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='investments')
    category = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    acquired_value = models.DecimalField(max_digits=10, decimal_places=2)
    acquired_date = models.DateField(default=timezone.now)
    recent_value = models.DecimalField(max_digits=10, decimal_places=2)
    recent_date = models.DateField(default=timezone.now, blank=True, null=True)

    def created(self):
        self.acquired_date = timezone.now()
        self.save()

    def updated(self):
        self.recent_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.customer)

    def results_by_investment(self):
        return self.recent_value - self.acquired_value


class Stock(models.Model):
    #user = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='stock')
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='stocks')
    symbol = models.CharField(max_length=10)
    name = models.CharField(max_length=50)
    shares = models.DecimalField(max_digits=10, decimal_places=1)
    purchase_price = models.DecimalField(max_digits=10, decimal_places=2)
    purchase_date = models.DateField(default=timezone.now, blank=True, null=True)

    def created(self):
        self.recent_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.customer)

    def current_stock_price(self):
        #json_data = {}
        symbol_f = str(self.symbol)
        main_api = 'http://api.marketstack.com/v1/eod?'
        api_key = 'access_key=dcc8dabbef057047184c033622bfb1a2&limit=1&symbols='
        url = main_api + api_key + symbol_f
        json_data = requests.get(url).json()
        open_price = float(json_data["data"][0]["open"])
        share_value = open_price
        return share_value

    def current_stock_value(self):
        return float(self.current_stock_price()) * float(self.shares)

    def initial_stock_value(self):
        return self.shares * self.purchase_price

    def final_result(self):
        return float(self.current_stock_value()) - float(self.initial_stock_value())

efs/portfolio/forms.py
from django import forms
from .models import Customer, Stock, Investment


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('cust_number', 'name', 'address', 'city', 'state', 'zipcode', 'email', 'cell_phone',)


class StockForm(forms.ModelForm):
    class Meta:
        model = Stock
        fields = ('customer', 'symbol', 'name', 'shares', 'purchase_price', 'purchase_date',)


class InvestmentForm(forms.ModelForm):
    class Meta:
        model = Investment
        fields = ('customer','category', 'description', 'acquired_value', 'acquired_date', 'recent_value','recent_date')

efs/portfolio/views.py
import decimal

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import get_template
from django.views import generic
from django.db.models import Sum
try:
    import simplejson as json
except ImportError:
    import json
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .serializers import CustomerSerializer
from .models import *
from .forms import *
from django.views.generic import View
from .utils import render_to_pdf
from django.contrib.auth.decorators import login_required, user_passes_test
import json

# def customer_list(request):
#     customer = Customer.objects.filter(created_date__lte=timezone.now())
#     return render(request, 'portfolio/customer_list.html',
#                   {'customers': customer})
#
#
# def customer_edit(request, pk):
#     customer = get_object_or_404(Customer, pk=pk)
#     if request.method == "POST":
#         # update
#         form = CustomerForm(request.POST, instance=customer)
#         if form.is_valid():
#             customer = form.save(commit=False)
#             customer.updated_date = timezone.now()
#             customer.save()
#             customer = Customer.objects.filter(created_date__lte=timezone.now())
#             return render(request, 'portfolio/customer_list.html',
#                           {'customers': customer})
#     else:
#         # edit
#         form = CustomerForm(instance=customer)
#     return render(request, 'portfolio/customer_edit.html', {'form': form})
#
#
# def customer_delete(request, pk):
#     customer = get_object_or_404(Customer, pk=pk)
#     customer.delete()
#     return redirect('portfolio:customer_list')
#
from .serializers import CustomerSerializer

now = timezone.now()


def home(request):
    return render(request, 'portfolio/home.html',
                  {'portfolio': home})


@login_required
def customer_list(request):
    customer = Customer.objects.filter(created_date__lte=timezone.now())
    return render(request, 'portfolio/customer_list.html',
                  {'customers': customer})


@user_passes_test(lambda user: user.is_superuser or user.is_FinancialAdvisor)
@login_required
def customer_edit(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    if request.method == "POST":
        # update
        form = CustomerForm(request.POST, instance=customer)
        if form.is_valid():
            customer = form.save(commit=False)
            customer.updated_date = timezone.now()
            customer.save()
            customer = Customer.objects.filter(created_date__lte=timezone.now())
            return render(request, 'portfolio/customer_list.html',
                          {'customers': customer})
    else:
        # edit
        form = CustomerForm(instance=customer)
    return render(request, 'portfolio/customer_edit.html', {'form': form})


@user_passes_test(lambda user: user.is_superuser or user.is_FinancialAdvisor)
@login_required
def customer_delete(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    customer.delete()
    return redirect('portfolio:customer_list')


@login_required
def stock_list(request):
    stocks = Stock.objects.filter(purchase_date__lte=timezone.now())
    return render(request, 'portfolio/stock_list.html', {'stocks': stocks})


@user_passes_test(lambda user: user.is_superuser or user.is_FinancialAdvisor)
@login_required
def stock_new(request):
    if request.method == "POST":
        form = StockForm(request.POST)
        if form.is_valid():
            stock = form.save(commit=False)
            stock.created_date = timezone.now()
            stock.save()
            stocks = Stock.objects.filter(purchase_date__lte=timezone.now())
            return render(request, 'portfolio/stock_list.html',
                          {'stocks': stocks})
    else:
        form = StockForm()
        # print("Else")
    return render(request, 'portfolio/stock_new.html', {'form': form})


@user_passes_test(lambda user: user.is_superuser or user.is_FinancialAdvisor)
@login_required
def stock_edit(request, pk):
    stock = get_object_or_404(Stock, pk=pk)
    if request.method == "POST":
        form = StockForm(request.POST, instance=stock)
        if form.is_valid():
            stock = form.save()
            # stock.customer = stock.id
            stock.updated_date = timezone.now()
            stock.save()
            stocks = Stock.objects.filter(purchase_date__lte=timezone.now())
            return render(request, 'portfolio/stock_list.html', {'stocks': stocks})
    else:
        # print("else")
        form = StockForm(instance=stock)
    return render(request, 'portfolio/stock_edit.html', {'form': form})


@user_passes_test(lambda user: user.is_superuser or user.is_FinancialAdvisor)
@login_required
def stock_delete(request, pk):
    stock = get_object_or_404(Stock, pk=pk)
    stock.delete()
    return redirect('portfolio:stock_list')


@login_required
def investment_list(request):
    investment = Investment.objects.all()
    return render(request, 'portfolio/investment_list.html', {'investment': investment})


@user_passes_test(lambda user: user.is_superuser or user.is_FinancialAdvisor)
@login_required
def investment_edit(request, pk):
    investment = get_object_or_404(Investment, pk=pk)
    if request.method == 'POST':
        form = InvestmentForm(request.POST, instance=investment)
        if form.is_valid():
            investmentform = form.save(commit=False)
            investmentform.save()
            messages.success(request, f'Your Customer has been updated')
            return redirect('/investment_list/')

    else:
        # edit
        investmentform = InvestmentForm(instance=investment)
        return render(request, 'portfolio/investment_edit.html', {'investmentform': investmentform})


@user_passes_test(lambda user: user.is_superuser or user.is_FinancialAdvisor)
@login_required
def investment_new(request):
    if request.method == 'POST':
        form = InvestmentForm(request.POST)
        if form.is_valid():
            investmentform = form.save(commit=False)
            investmentform.created_date = timezone.now()
            investmentform.save()
            messages.success(request, f'Your New Board has been updated')
            return redirect('/investment_list/')

    else:
        # edit
        investmentform = InvestmentForm()
        return render(request, 'portfolio/investment_new.html', {'investmentform': investmentform})


@user_passes_test(lambda user: user.is_superuser or user.is_FinancialAdvisor)
@login_required
def investment_delete(request, pk):
    investment = get_object_or_404(Investment, pk=pk)
    investment.delete()
    return redirect('/investment_list/')


@login_required
def portfolio(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    customers = Customer.objects.filter(created_date__lte=timezone.now())
    investments = Investment.objects.filter(customer=pk)
    stocks = Stock.objects.filter(customer=pk)
    sum_recent_value = Investment.objects.filter(customer=pk).aggregate(Sum('recent_value'))
    sum_acquired_value = Investment.objects.filter(customer=pk).aggregate(Sum('acquired_value'))
    # overall_investment_results = sum_recent_value-sum_acquired_value
    # Initialize the value of the stocks
    sum_current_stocks_value = 0
    sum_of_initial_stock_value = 0
    sum_current_investment_value = 0
    sum_of_initial_investment_value = 0

    # Loop through each stock and add the value to the total
    for stock in stocks:
        sum_current_stocks_value += stock.current_stock_value()
        sum_of_initial_stock_value += stock.initial_stock_value()

    result = decimal.Decimal(sum_current_stocks_value) - (sum_of_initial_stock_value)

    for investment in investments:
        sum_current_investment_value += investment.recent_value
        sum_of_initial_investment_value += investment.acquired_value

    result1 = sum_current_investment_value - sum_of_initial_investment_value

    Total_current_investments = float(sum_current_stocks_value) + float(sum_current_investment_value)
    Total_initial_investments = float(sum_of_initial_investment_value) + float(sum_of_initial_stock_value)
    Grand_total = result + result1

    return render(request, 'portfolio/portfolio.html', {'customer': customer,
                                                        'customers': customers,
                                                        'investments': investments,
                                                        'stocks': stocks,
                                                        'sum_acquired_value': sum_acquired_value,
                                                        'sum_recent_value': sum_recent_value,
                                                        'result': result,
                                                        'sum_current_stocks_value': sum_current_stocks_value,
                                                        'sum_of_initial_stock_value': sum_of_initial_stock_value,
                                                        'sum_current_investment_value': sum_current_investment_value,
                                                        'sum_of_initial_investment_value': sum_of_initial_investment_value,
                                                        'result1': result1,
                                                        'Total_current_investments': Total_current_investments,
                                                        'Total_initial_investmensts': Total_initial_investments,
                                                        'Grand_total': Grand_total})


class CustomerList(APIView):
    def get(self, request):
        customers_json = Customer.objects.all()

efs/portfolio/templates/portfolio/base.html
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,
    initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"\ integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>
    <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4" style=" height: 80px;">
      <a class="navbar-brand" href="{% url 'portfolio:home' %}">Eagle Financial Services</a>

        <ul class="nav nav-tabs" id="myTab" role="tablist">
         <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'portfolio:customer_list' %}">Customers</a>
            <a class="dropdown-item" href="{% url 'portfolio:investment_list' %}">Investment</a>
          <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'portfolio:stock_list' %}">Stocks</a>
          </div>
        </li>
        </ul>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab"></div>
      <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab"></div>
      <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab"></div>
    </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse"
              data-target="#navbarCollapse" aria-controls="navbarCollapse"
      aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        {% if user.is_authenticated %}
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link dropdown-toggle" href="#" id="userMenu"\
              data-toggle="dropdown" aria-haspopup="true" aria-expanded\
              ="false">
                {{ user.username }}
              </a>
              <div class="dropdown-menu dropdown-menu-right"
              aria-labelledby="userMenu">
                <a class="dropdown-item" href="{% url 'password_change' %}">Change password</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'logout' %}">
                Log Out</a>
              </div>
            </li>
          </ul>
          </ul>
        {% else %}
          <form class="form-inline ml-auto">
            <a href="{% url 'login' %}" class="btn btn-outline-secondary">
            Log In</a>
            <a href="{% url 'signup' %}" class="btn btn-primary ml-2">
            Sign up</a>
          </form>
        {% endif %}
      </div>
    </nav>
    <div class="container">
      {% block content %}
      {% endblock content %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  </body>
</html>

efs/portfolio/templates/portfolio/customer_list.html
{% extends 'portfolio/base.html' %}

{% block content %}

    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Eagle Financial Services, your Midwest Financial Services Partner.
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% if request.user.is_superuser or request.user.is_FinancialAdvisor %}
    <div class="row">
        <h2 style="padding-left: 15Px">Customer Information</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Customer Number</th>
                <th>Name</th>
                <th>Address</th>
                <th>City</th>
                <th>State</th>
                <th>Zip</th>
                <th>Primary Email</th>
                <th>Cell Phone</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for customer in customers %}
                <tr>
                    <td>{{ customer.cust_number }}</td>
                    <td>{{ customer.name }}</td>
                    <td>{{ customer.address }}</td>
                    <td>{{ customer.city }}</td>
                    <td>{{ customer.state }}</td>
                    <td>{{ customer.zipcode }}</td>
                    <td>{{ customer.email }}</td>
                    <td>{{ customer.cell_phone }}</td>
                    <td><a href= "{% url 'portfolio:customer_edit' pk=customer.pk %}"  class="btn btn-warning">Edit</a>
                    <td><a href="{% url 'portfolio:customer_delete' pk=customer.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>
                    <td><a href="{% url 'portfolio:portfolio' pk=customer.pk %}"
                           class="btn btn-primary">Portfolio</a>

                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
    {% else %}
    <div  class="table-responsive text-nowrap">
      <table class="table table-striped">
        <thead class="thead-light">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Customer Number</th>
            <th scope="col">Name</th>
            <th scope="col">Address</th>
            <th scope="col">City</th>
            <th scope="col">State</th>
            <th scope="col">Zip</th>
            <th scope="col">Primary Email</th>
            <th scope="col">Cell Phone</th>
            <th colspan="3" style=" text-align: center;">Actions</th>
          </tr>
        </thead>
        <tbody>
         {% for customer in customer %}
            {% if customer.user == request.user %}
                <tr>
                  <th scope="row">{{forloop.counter}}</th>
                   <td>{{ customer.cust_number }}</td>
                   <td>{{ customer.name }}</td>
                   <td>{{ customer.address }}</td>
                   <td>{{ customer.city }}</td>
                   <td>{{ customer.state }}</td>
                   <td>{{ customer.zipcode }}</td>
                   <td>{{ customer.email }}</td>
                   <td>{{ customer.cell_phone }}</td>
                   <td><a href="{% url 'portfolio:portfolio' pk=customer.pk %}" class="btn btn-primary">Portfolio</a>
                </tr>
            {% endif  %}
         {% endfor %}
        </tbody>
      </table>
    </div>
    </body>
    </html>
{% endif  %}
{% endblock %}
   

efs/portfolio/templates/portfolio/investment_list.html
{% extends 'portfolio/base.html' %}

{% block content %}
  <div class="card mb-3"style="max-width: 50rem;color:#4B7381;">
  <div class="card-body">
    <h5 class="card-title"><b>Investment Information</b></h5>
    <p class="card-text">Eagle Financial Services, your Midwest Financial Services Partner.</p>
  </div>
</div>
{% if request.user.is_superuser or request.user.is_FinancialAdvisor %}
<div  class="table-responsive text-nowrap">
  <table class="table table-striped">
    <thead class="thead-light">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Customer</th>
        <th scope="col">Category</th>
        <th width="50%">Description</th>
        <th scope="col">Acquired Value</th>
        <th scope="col">Acquired Date</th>
        <th scope="col">Recent Value</th>
        <th scope="col">Recent Date</th>
        <th colspan="3" style=" text-align: center;">Actions</th>
      </tr>
    </thead>
    <tbody>
     {% for investment in investment %}
        <tr>
          <th scope="row">{{forloop.counter}}</th>
           <td>{{ investment.user }}</td>
           <td>{{ investment.category }}</td>
           <td>{{ investment.description }}</td>
           <td>{{ investment.acquired_value }}</td>
           <td>{{ investment.acquired_date }}</td>
           <td>{{ investment.recent_value }}</td>
           <td>{{ investment.recent_date }}</td>
           <td><a href="{% url 'portfolio:investment_edit' pk=investment.pk %}" class="btn btn-warning">Edit</a>
           <td><a href="{% url 'portfolio:investment_delete' pk=investment.pk %}" onclick="return confirm('Are you sure you want to delete?')" class="btn btn-danger">Delete</a>
           </td>
        </tr>
     {% endfor %}
    </tbody>
  </table>
    <div class="row">
        <a href="{% url 'portfolio:investment_new' %}"><span class="btn btn-primary">Add Investment</span></a>
    </div>
</div>
{% else %}
<div  class="table-responsive text-nowrap">
  <table class="table table-striped">
    <thead class="thead-light">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Customer</th>
        <th scope="col">Category</th>
        <th scope="col">Description</th>
        <th scope="col">Acquired Value</th>
        <th scope="col">Acquired Date</th>
        <th scope="col">Recent Value</th>
        <th scope="col">Recent Date</th>
      </tr>
    </thead>
    <tbody>
     {% for investment in investment %}
         {% if investment.user.user == request.user %}
            <tr>
              <th scope="row">{{forloop.counter}}</th>
               <td>{{ investment.user }}</td>
               <td>{{ investment.category }}</td>
               <td>{{ investment.description }}</td>
               <td>{{ investment.acquired_value }}</td>
               <td>{{ investment.acquired_date }}</td>
               <td>{{ investment.recent_value }}</td>
               <td>{{ investment.recent_date }}</td>
            </tr>
         {% endif  %}
     {% endfor %}
    </tbody>
  </table>
</div>
{% endif  %}
{% endblock content %}

efs/portfolio/templates/portfolio/stock_list.html
{% extends 'portfolio/base.html' %}
{% block content %}
    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Eagle Financial Services, your Midwest Financial Services Partner.
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Stocks Information</h2>
    </div>
    {% if request.user.is_superuser or request.user.is_FinancialAdvisor %}
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Customer number</th>
                <th>Symbol</th>
                <th>Name</th>
                <th>Shares</th>
                <th>Purchase Price</th>
                <th>Purchase Date</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for stock in stocks %}
                <tr>
                    <td>{{ stock.customer }}</td>
                    <td>{{ stock.symbol }}</td>
                    <td>{{ stock.name }}</td>
                    <td>{{ stock.shares }}</td>
                    <td>{{ stock.purchase_price }}</td>
                    <td>{{ stock.purchase_date }}</td>
                     <td><a href="{% url 'portfolio:stock_edit' pk=stock.pk %}"
                           class="btn btn-warning">Edit</a></td>

                    <td><a href="{% url 'portfolio:stock_delete' pk=stock.pk %}" onclick="return confirm('Are you sure you want to delete?')" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
     <div class="row">
         <a href="{% url 'portfolio:stock_new' %}" class="row"><span
                    class="btn btn-primary">Add Stock</span></a>
     </div>
    </div>
  {% else %}
<div  class="table-responsive text-nowrap">
      <table class="table table-striped">
        <thead class="thead-light">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Customer Number</th>
            <th scope="col">Symbol</th>
            <th scope="col">Name</th>
            <th scope="col">Shares</th>
            <th scope="col">Purchase Price</th>
            <th scope="col">Purchase Date</th>
          </tr>
        </thead>
        <tbody>
         {% for stock in stock %}
          {% if  stock.user.user == request.user %}
            <tr>
              <th scope="row">{{forloop.counter}}</th>
               <td>{{ stock.user }}</td>
               <td>{{ stock.symbol }}</td>
               <td>{{ stock.name }}</td>
               <td>{{ stock.shares }}</td>
               <td>{{ stock.purchase_price }}</td>
               <td>{{ stock.purchase_date }}</td>
            </tr>
          {% endif  %}
         {% endfor %}
        </tbody>
      </table>
    {% endif  %}
    {% endblock content %}